// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://ehmdwwuhhumgxhsjvvrr.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVobWR3d3VoaHVtZ3hoc2p2dnJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNzI1MDgsImV4cCI6MjA5MDY0ODUwOH0.qmzYKaoUluhbwsQgKR9yzuM6wyW7qA7XbEP8LG1fnjk';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

// DEBUG TEMPORÁRIO — remover depois
if (typeof window !== 'undefined') {
  // @ts-expect-error debug
  window.supabase = supabase;
}